# Netlify configuration for SA IS A MOVIE landing page
[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--version"

# Functions configuration
functions = "netlify/functions"

# Admin route redirect for Decap CMS
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

# SPA fallback for React app (exclude admin routes)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
#[dev]
#  command = "pnpm run dev" # Command to start your dev server
#  port = 5173 # Port that the dev server will be listening on (Vite default)
#  publish = "dist" # Folder with the static content for _redirect file

# Cache control headers for favicon files
[[headers]]
  for = "/favicon*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/apple-touch-icon*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
