# Netlify configuration for SA IS A MOVIE landing page
[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NODE_ENV = "production"
  NPM_FLAGS = "--version"
  # Contentful environment variables (set these in Netlify dashboard)
  # VITE_CONTENTFUL_SPACE_ID = "your-space-id"
  # VITE_CONTENTFUL_ACCESS_TOKEN = "your-access-token"
  # Secrets scanning configuration - ignore Auth0 env vars as they're expected in client-side code
  SECRETS_SCAN_OMIT_KEYS = "VITE_AUTH0_DOMAIN,VITE_AUTH0_CLIENT_ID,AUTH0_CLIENT_ID"

# Configure secrets scanning to ignore Auth0 environment variables
# These are expected to be in the build output for client-side authentication
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Functions configuration
functions = "netlify/functions"

# Admin route redirect for Decap CMS with role-based access
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  conditions = {Role = ["admin", "editor"]}

# Block unauthorized access to admin
[[redirects]]
  from = "/admin/*"
  to = "/login"
  status = 401
  conditions = {Role = ["!admin", "!editor"]}

# SPA fallback for React app (exclude admin routes)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
#[dev]
#  command = "pnpm run dev" # Command to start your dev server
#  port = 5173 # Port that the dev server will be listening on (Vite default)
#  publish = "dist" # Folder with the static content for _redirect file

# Cache control headers for favicon files
[[headers]]
  for = "/favicon*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/apple-touch-icon*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
